baseurl = "/"
languageCode = "en-us"
theme = "terminal"

[pagination]
pagerSize = 5

[params]
contentTypeName = "posts"
themeColor = "orange"
showMenuItems = 0
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true
favicon = "favicon.ico"
ReadMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en]
languageName = "English"
title = "archit.xyz // Archit Khode"
subtitle = "Software Engineer"
keywords = "archit, khode, software, engineer, archit.xyz"
menuMore = "Show more"
ReadMore = "Read more"
readOtherPosts = "Read other posts"

[languages.en.params.logo]
logoText = "archit.xyz"
logoHomeLink = "/"

[sitemap]
changeFreq = ''
disable = false
filename = 'sitemap.xml'
priority = -1

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = false
    lineNos = false
    style = "github-dark"
